// commands/imagine.js — !imagine / !vẽ / !ve: DALL·E 3 image generation

import { EmbedBuilder } from "discord.js";
import { log } from "../utils/logger.js";

export async function handleImagine(msg, prompt, { ai }) {
  if (!prompt) {
    return msg.reply({ content: "Cho em prompt đi, vd: `!imagine mèo phi hành gia phong cách cyberpunk`", allowedMentions: { repliedUser: false } });
  }

  const waitMsg = await msg.reply({ content: "🎨 Đang vẽ... chờ chút", allowedMentions: { repliedUser: false } });

  try {
    const url = await ai.generateImage(prompt);
    const embed = new EmbedBuilder()
      .setTitle(`🎨 ${prompt.slice(0, 250)}`)
      .setColor(0xE91E63)
      .setImage(url)
      .setFooter({ text: "Generated by DALL·E 3" });
    await waitMsg.edit({ content: null, embeds: [embed] });
  } catch (err) {
    log.error("IMAGINE", err.message);
    await waitMsg.edit({ content: "Vẽ thất bại rồi — có thể prompt bị chặn hoặc lỗi API, thử prompt khác xem 😵" });
  }
}
